name: CI

# Run on pull requests. And on master itself.
on:
  push:
    branches:
      - master
  pull_request:


jobs:
  TestLinux:
    name: Linux, Python ${{ matrix.python }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.12"
          - python: "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install GDAL
        run: |
          sudo apt update
          sudo apt install --yes --no-install-recommends python3-gdal

      - name: Install python dependencies
        shell: bash
        run: |
          pip install .[test]
          pip list

      - name: Run tests
        shell: bash
        run: |
          pytest
